### PR TITLE
New depot system

### PR DESCRIPTION
**Pull request by comedinha**
fuck squash

### CODE REVIEW

**Comment by Tazer89** [comment]
Does it works?

**Comment by Tazer89** [comment]
For some reason i dont get depot box I in the depot.

**Comment by comedinha** [comment]
You need use this items.otb https://github.com/Tulioh/forgottenserver/blob/update_to_1090/data/items/items.otb

**Comment by Alissonfgp** [comment]
@comedinha Check It
I found some bugs and made some changes...
https://github.com/Alissonfgp/forgottenserver/commit/40f8154f1095246411f30ddc0f10064b62f982c3

**Pull request closed without merging**
